version: '3.5'
services:
  client:
    container_name: estimate-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: always
  redis:
    container_name: estimate-redis
    image: 'redis:5.0.1-alpine'
    ports:
      - '6379:6379'
    volumes:
      - './data:/data'
    restart: always
